### PR TITLE
Add beta channel support

### PR DESCRIPTION
**Pull request by 190n**
I added beta channel support with a CLI flag (`-b` or `--beta`) and a brief help message.

### CODE REVIEW

**Comment by 190n** [comment]
Hello?

**Comment by mehcode** [comment]
Hey .. Sorry. Been busy. 

It doesn't look like your change actually gets the beta? It just reads the whole page and gets the first entry.. which could be the beta.

**Comment by 190n** [comment]
Hi. Thanks for getting back.

I see that bug, I think I might know a fix for it. However, it's exam week and I probably won't be able to get back until Wednesday.

**Comment by 190n** [comment]
I think it does install the beta?
screenshot from 2015-12-26 10 49 25

and then

screenshot from 2015-12-26 10 50 05

**Comment by 190n** [comment]
...

**Comment by simonkberg** [comment]
@190n the issue is that you're getting the latest version from the releases page. It could as well be the latest stable `1.5.4` while the latest beta is `1.6.0-beta6` (for example), simply because the beta version was released before the latest stable. You also compare version with the stable executable, thus every run of `atom-updater` with the beta-flag would trigger a re-install. 

I've submitted a PR with a better implementation here: #8

**Comment by 190n** [comment]
@simonkberg Ok thanks!

**Pull request closed without merging**
